/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: {
          lightGray: "#AAAAAA",
          limeGreen: "#A6B200",
          oliveGray: "#8B8C78",
          lightLime: "#D7E145",
          black: "#000000",
          darkGray: "#737373",
          mediumGray: "#B7B7B7",
          footer: "#646558",
          footerText: "#B6B994",
          input: "#E6E6E6",
          inputText: "#494949",
        },
        category: {
          cyan: "#8FEEFF",
          limeYellow: "#D3EE79",
          green: "#69D170",
          lightBlue: "#87CDFF",
          mediumGreen: "#3CCC89",
          lightPink: "#FACAEA",
          lightOrange: "#FFD9B4",
          paleYellow: "#FAFACA",
          teal: "#B5F0F2",
          pink: "#FF8BC3",
          lightGray: "#D3D3D3",
          softYellow: "#FFED89",
          lavender: "#E5C2FF",
          peach: "#FFBBA3",
          violet: "#C96BFF",
          paleBlue: "#C2D4FF",
          softOrange: "#FECD94",
          gray: "#D2D2D2",
          beige: "#DCC6B8",
        },
        workCategory: {
          beige: "#DACB91",
          coral: "#FDA3A0",
          pinkPurple: "#DF90E7",
          yellow: "#FFFB84",
          lightGray: "#E4E4E4",
          limeGreen: "#AFDF7F",
          peach: "#FFC8AB",
          skyBlue: "#9ED7FF",
          mediumBlue: "#75ACFF",
          gray: "#C8C8C8",
        },
      },
    },
  },
  plugins: [],
};
