# Generated by Django 4.2.14 on 2024-08-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="end_date",
            field=models.DateField(help_text="예약 종료 날짜. 형식: YYYY-MM-DD."),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_date",
            field=models.DateField(help_text="예약 시작 날짜. 형식: YYYY-MM-DD."),
        ),
    ]
