# Generated by Django 4.2.14 on 2024-08-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="create_at", new_name="created_at",
        ),
    ]
