# Generated by Django 4.2.14 on 2024-08-25 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("senior", "0002_alter_senior_intro_image"),
        ("review", "0002_review_seniorid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="seniorId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="senior.senior"
            ),
        ),
    ]
