# Generated by Django 4.2.14 on 2024-08-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_rename_create_at_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_image",
            field=models.ImageField(default=None, upload_to="review_images/"),
        ),
    ]
