# Generated by Django 4.2.14 on 2024-08-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_rename_userid_review_usersid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="usersId", new_name="userId",
        ),
    ]
