# Generated by Django 4.2.14 on 2024-08-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="village_photo",
            field=models.ImageField(default=None, upload_to="village_images/"),
        ),
    ]
