# Generated by Django 4.2.14 on 2024-08-25 23:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0002_alter_village_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="village",
            name="create_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
