# Generated by Django 4.2.14 on 2024-08-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("village", "0002_alter_village_village_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="village", old_name="village_photo", new_name="village_image",
        ),
    ]
