# Generated by Django 4.2.14 on 2024-08-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("senior", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senior",
            name="intro_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="senior_images/intro/"
            ),
        ),
    ]
